future: true
drafts: true
unpublished: true

url: https://thisismaja.com

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      permalink: /posts/:slug


collections:
  archives:
    output: true
  products:
    output: true
  freebies:
    output: true
  pages:
    output: true
    all-posts: true
    permalink: /posts/:slug
  posts:
    output: true
    all-posts: true

sizes:
  - full
  - one-half
  - one-third
  - two-thirds

banner-heights:
  - vh-50
  - vh-70
  - vh-80
  - vh-90

image-heights:
  - landscape
  - square
  - portrait

block-classes:
  - light-bg
  - grey-bg
  - featured-bg
  - dark-bg

_options:
  heading_html:
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    underline: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    styles: /assets/editor.css
  body-content_html:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true
    bulletedlist: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    styles: /assets/editor.css
  content:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true
    bulletedlist: true
    styles: /assets/editor.css
  embed-code_html:
    embed: true

sass:
    sass_dir: _sass

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 16

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'


# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    slugify:
      mode: raw
      cased: true
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'archive-categories.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: ':cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/:cat'

  # Collection pages, omit to disable
  collections:
    layouts:
      - 'archive-categories.html'
    title: 'posts in :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'archive-tags.html'
    title: ':tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'


page_blocks: []
_array_structures:
  page_blocks:
    - label: Main Content
      icon: ballot
      value:
        _id: main-content
        name: Main Content
        block-class:
        maja-signoff: false
    - label: Image Banner
      icon: ballot
      value:
        _id: image-banner
        name: Image Banner
        background_image:
        banner-height:
        heading_html:
    - label: Image Gallery
      icon: ballot
      value:
        _id: image-gallery
        name: Image Gallery
        block-class:
        heading_html:
        gallery-images: []
    - label: Affiliate Gallery
      icon: ballot
      value:
        _id: affiliate-gallery
        name: Affiliate Gallery
        block-class:
        heading_html:
        affiliate-images: []
    - label: Slideshow Gallery
      name: Slideshow Gallery
      icon: ballot
      value:
        _id: slideshow-gallery
        block-class:
        slideshow-images: []
    - label: Text Block
      icon:
      value:
        _id: text-block
        name: Simple Text Block
        block-class:
        body-content_html:
        maja-signoff: false
    - label: Intro
      icon:
      value:
        _id: intro
        name: Intro Section
        block-class:
        image-1_path:
        image-2_path:
        intro-paragraph-emphasis:
        body-content_html:
  gallery-images:
    label: Gallery Image
    icon: collections
    value:
      background_image:
      image-height:
      body-content_html:
  affiliate-images:
    label: Affiliate Image
    icon: collections
    value:
      embed-code_html:
  slideshow-images:
    label: Slideshow Image
    icon: collections
    value:
      background_image:
